/*
389. Find the Difference

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

class Solution {
    public char findTheDifference(String s, String t) {
        char ret = t.charAt(0);
        for (int i = 1; i < t.length(); ++i) {
            ret ^= t.charAt(i);
        }
        
        for (int i = 0; i < s.length(); ++i) {
            ret ^= s.charAt(i);
        }
        
        return ret;
    }
}